services:
  db:
    image: postgres:16
    container_name: todolite_db
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - tododb_data:/var/lib/postgresql/data

volumes:
  tododb_data:
